apiVersion: v1
kind: Pod
metadata:
  name: pod-practice
spec:
  nodeSelector:
    kubernetes.io/hostname: worker-01
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: pvc-practice
