apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-new
  labels:
    type: test

spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: advanced
            operator: In
            values:
            - "true"
  hostPath:
    path: "/mnt/new_data"


